add_requires("doctest")

target("test_hello")
  set_kind("binary")
  set_group("tests")
  add_files("$(projectdir)/tests/test_hello.cpp")
  add_packages("doctest")

target("test_fileio")
  set_kind("binary")
  set_group("io")
  add_files("$(projectdir)/tests/io/test_file_io.cpp")
  add_packages("doctest")
  add_deps("bitdb")

target("test_hash_index")
  set_kind("binary")
  set_group("index")
  add_files("$(projectdir)/tests/index/test_hashmap_index.cpp")
  add_packages("doctest")
  add_deps("bitdb")

target("test_tree_index")
  set_kind("binary")
  set_group("index")
  add_files("$(projectdir)/tests/index/test_treemap_index.cpp")
  add_packages("doctest")
  add_deps("bitdb")

target("test_arena")
  set_kind("binary")
  set_group("utils")
  add_files("$(projectdir)/tests/utils/test_arena.cpp")
  add_packages("doctest")
  add_deps("bitdb")
